### ISSUE TITLE
Question about usage of BVT for retrieving list of objects intersected by a Ray

### ISSUE THREAD

**Issue by acolley** [rustsim/ncollide#88]
This isn't technically an issue with the library but I'm wondering about how to use the BVT structure (or indeed the DBVT structure) for retrieving a collection of objects that are intersected by a ray.

I could see from the nrays project that there used to be a `cast_ray` method on the BVT structure that provided an easy way to do this. Obviously this was built using an older version of ncollide as this no longer seems to exist and I can't see another way to do this.

I had a look at the `CollisionWorld` and this seems to be closer to what I need, but this is overkill for my use case.

Could someone enlighten me as to the best way to do what I want?

Thanks a lot for any help.

**Comment by acolley** [comment]
I should have read the documentation a little more closely but I have something worked out using the `RayInterferencesCollector` to gather a `Vec` of intersected objects with a ray.

What I'm still confused about though is how to get the closest intersecting object from this vector, at the moment I'm just assuming it's the first element. Or is there another way of querying for this information directly?

**Comment by sebcrozet** [comment]
The `BVT` can be browsed in two manners.

What you probably did is to use the `RayInterferencesCollector` together with the `.visit(...)` method of the tree. This will collect all the objects which have their bounding volume intersect the ray. Then, you still have to check that the ray actually intersects the collected body performing a ray cast on each of them (and if you need to, select the one with smallest time of impact). Also note that the first element is **not** the closest intersecting object (since no ray cast is done on the objects themselves) nor the closest bounding volume.

The second way to use the `BVT` is using the `.best_first_search(...)` method, which is what you should do if you are seeking the first hit only. You need to feed this method the `RayIntersectionCostFn` structure. This will work only if your objects implement the `LocalRayCast` trait (which will be removed in favor of `RayCast` soon btw. See the second comment of #87). The `.best_first_search(...)`method is not yet implemented for the `DBVT` though; so you might want to go with the first option if you need it.

This second option is pretty new (relative to the time when I first wrote the documentation on `ncollide.org`, so unfortunately, I did not have the time to document it yet.

**Comment by acolley** [comment]
Thanks for the informative reply! Looks like `best_first_search()` is ideally what I want but since I'm using a DBVT I'll have to go with the other method for now. Good to know there's a choice for various tradeoffs to be made though.

**Comment by bonsairobo** [comment]
@sebcrozet Looks like `RayIntersectionCostFn` was removed in c0052bb21cbd83f37fb9225c2b03e18f76b87922.

Is `BestFirstVisitor` the new solution to this use case? Seeing as 3D picking via ray tracing to the closest object is a common use case, the documentation probably deserves a refresher.

I'm looking through the API reference trying to find how to ray cast at a BVT of AABBs. I see that only `CompositeClosestPointVisitor` implements `BestFirstVisitor`, but I fail to see how this solves the ray casting problem.

**Comment by bonsairobo** [comment]
Does this seem like it would work?

Side note: why does `toi_with_ray` take an isometry? Can't the user transform their own ray? I'm guessing most people will just pass the identity.

    struct EarliestToiRayCast {
        pub ray: Ray<f32>,
        pub solid: bool,
        pub tfm: Isometry3<f32>,
    }

    impl<T, B> BestFirstVisitor<f32, T, B> for EarliestToiRayCast
    where
        B: RayCast<f32>
    {
        type Result = T;

        fn visit_bv(&mut self, bv: &B) -> BestFirstBVVisitStatus<f32> {
            let solid = true;
            if let Some(toi) = bv.toi_with_ray(&self.tfm, &self.ray, self.solid) {
                BestFirstBVVisitStatus::ContinueWithCost(toi)
            } else {
                BestFirstBVVisitStatus::Stop
            }
        }

        fn visit_data(
            &mut self, data: &T
        ) -> BestFirstDataVisitStatus<f32, T> {
            BestFirstDataVisitStatus::Continue
        }
    }

**Comment by bonsairobo** [comment]
I just realized the above implementation doesn't even work because if you never return `BestFirstDataVisitStatus::ContinueWithResult` then you get a `None` result. I only care about the cost in `visit_bv`. So I guess I need to keep state so I can remember which data match to which volumes so I can provide the right cost? This seems a bit convoluted.

**Comment by sebcrozet** [comment]
@bonsairobo Hi! The disappearance of `RayIntersectionCostFn` is surprising. It seems I forgot to re-add an equivalent based on the new design. I'll address this next saturday.

> Should I implement my own BestFirstVisitor that uses toi_with_ray to determine the cost?

That would be the right approach, yes.

> Side note: why does toi_with_ray take an isometry? Can't the user transform their own ray? I'm guessing most people will just pass the identity.

The transform represents the transform of the shape that the ray is being cast on. That's needed because most shapes of `ncollide` do not contain their world-position.

> I just realized the above implementation doesn't even work because if you never return BestFirstDataVisitStatus::ContinueWithResult then you get a None result. 

The `BestFirstDataVisitStatus::ContinueWithResult` should be returned by `visit_data`. The idea is that the tree is based on bounding volumes to accelerate the ray-cast. The role of `visit_data` is to perform a ray-cast on the actual shapes bounded by those bounding-volumes to return a result. Though if your `T` is not ray-castable (which was already a requirement for the old `RayIntersectionCostFn` to work), I guess the current design is a bit limiting.

I solution would be to modify the `BestFirstBVVisitStatus` enum so it also has the `ContinueWithResult` and `ExitEarlyWithResult` variants (just like `BestFirstDataVisiStatus`)!

**Comment by bonsairobo** [comment]
@sebcrozet Thanks for the response! I like you idea of modifying the `BestFirstBVVisitStatus` enum. That would greatly simplify my code.

**Comment by bonsairobo** [comment]
Actually, one issue with that new enum is that `visit_bv` doesn't see the data associated with the bounding volume, so it wouldn't know what result to return.

**Comment by bonsairobo** [comment]
I guess I really want something like `BestFirstVisitor` that only assigns cost to the bounding volumes and lets you visit the entire node (bv and data) at once. Another option is having an extra `BestFirstDataVisitStatus` variant like `ContinueWithBVCost(result)` that means, "I'm just going to use the cost from `visit_bv`, but here's the result if that cost is good."

**Comment by sebcrozet** [comment]
@bonsairobo  Now that I thought about this further, we should just combine `visit_bv` and `visit_data` into a single method: `fn visit(&mut self, bv: &BV, data: Option<&B>) -> BestFirstBVVisitStatus<N>;`.

We actually already do something similar for the simultaneous tree traversal [there](https://github.com/rustsim/ncollide/blob/master/src/partitioning/visitor.rs#L26). That way, this `visit` method is free to return whatever cost it wants, potentially with a result if it exists.

**Comment by bonsairobo** [comment]
Another thing that would be nice is if `best_first_search` returned the leaf ID along with the result. I often need to find something in a DBVT then remove it.

**Comment by bonsairobo** [comment]
For now, I'm just implementing `Visitor` instead of `BestFirstVisitor`. I can more simply keep track of the least cost on my own this way. I still think it's a good idea to combine `visit_bv` and `visit_data`.
